if (!(Test-Path -Path C:\temp )) { New-Item -ItemType directory -Path C:\temp };secedit /export /cfg C:\temp\secpol.cfg;
Write-Output '====';
[System.Net.Dns]::GetHostName();
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'PasswordHistorySize =';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'MaximumPasswordAge =';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'MinimumPasswordAge =';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'MinimumPasswordLength =';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'PasswordComplexity =';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'ClearTextPassword =';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'ForceLogoffWhenHourExpire =';Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows Nt\Currentversion' -Name 'ProductName';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System' -Name 'NoConnectedUser';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'LimitBlankPasswordUse';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Lsa' -Name 'SCENoApplyLegacyAuditPolicy';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Lsa' -Name 'CrashOnAuditFail';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows Nt\Currentversion\Winlogon' -Name 'AllocateDASD';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Print\Providers\Lanman Print Services\Servers' -Name 'AddPrinterDrivers';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Netlogon\Parameters' -Name 'RequireSignOrSeal';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Netlogon\Parameters' -Name 'sealsecurechannel';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Netlogon\Parameters' -Name 'signsecurechannel';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Netlogon\Parameters' -Name 'disablepasswordchange';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Netlogon\Parameters' -Name 'MaximumPasswordAge';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Netlogon\Parameters' -Name 'requirestrongkey';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System' -Name 'DontDisplayLastUserName';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System' -Name 'DisableCAD';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System' -Name 'InactivityTimeoutSecs';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows Nt\Currentversion\Winlogon' -Name 'passwordexpirywarning';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows Nt\Currentversion\Winlogon' -Name 'ForceUnlockLogon';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows Nt\Currentversion\Winlogon' -Name 'scremoveoption';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Lanmanworkstation\Parameters' -Name 'RequireSecuritySignature';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Lanmanworkstation\Parameters' -Name 'EnableSecuritySignature';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Lanmanworkstation\Parameters' -Name 'EnablePlainTextPassword';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Lanmanserver\Parameters' -Name 'autodisconnect';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Lanmanserver\Parameters' -Name 'requiresecuritysignature';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Lanmanserver\Parameters' -Name 'enablesecuritysignature';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Lanmanserver\Parameters' -Name 'enableforcedlogoff';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Lanmanserver\Parameters' -Name 'SMBServerNameHardeningLevel';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Lsa' -Name 'RestrictAnonymousSAM';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Lsa' -Name 'RestrictAnonymous';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Lsa' -Name 'EveryoneIncludesAnonymous';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Lanmanserver\Parameters' -Name 'NullSessionPipes';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Securepipeservers\Winreg\Allowedexactpaths' -Name 'Machine';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\SecurePipeServers\Winreg\AllowedPaths' -Name 'Machine';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\SecurePipeServers\Winreg\AllowedPaths' -Name 'Machine';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\SecurePipeServers\Winreg\AllowedPaths' -Name 'Machine';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\SecurePipeServers\Winreg\AllowedPaths' -Name 'Machine';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Lanmanserver\Parameters' -Name 'restrictnullsessaccess';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name 'restrictremotesam';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Lanmanserver\Parameters' -Name 'NullSessionShares';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Lsa' -Name 'ForceGuest';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Lsa' -Name 'UseMachineID';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Lsa\Msv1_0' -Name 'allownullsessionfallback';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Lsa\Pku2U' -Name 'AllowOnlineID';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System\Kerberos\Parameters' -Name 'SupportedEncryptionTypes';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Lsa' -Name 'NoLMHash';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'LMCompatibilityLevel';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Ldap' -Name 'LDAPClientIntegrity';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Lsa\Msv1_0' -Name 'NTLMMinClientSec';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Lsa\Msv1_0' -Name 'NTLMMinServerSec';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System' -Name 'ShutdownWithoutLogon';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Session Manager\Kernel' -Name 'ObCaseInsensitive';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Session Manager' -Name 'ProtectionMode';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Session Manager\Subsystems' -Name 'Optional';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System' -Name 'FilterAdministratorToken';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System' -Name 'ConsentPromptBehaviorAdmin';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System' -Name 'ConsentPromptBehaviorUser';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System' -Name 'EnableInstallerDetection';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System' -Name 'EnableSecureUIAPaths';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System' -Name 'EnableLUA';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System' -Name 'PromptOnSecureDesktop';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System' -Name 'EnableVirtualization';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile' -Name 'EnableFirewall';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile' -Name 'DefaultInboundAction';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile' -Name 'DefaultOutboundAction';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile' -Name 'DisableNotifications';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile\Logging' -Name 'LogFilePath';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile\Logging' -Name 'LogFileSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile\Logging' -Name 'LogDroppedPackets';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile\Logging' -Name 'LogSuccessfulConnections';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Privateprofile' -Name 'EnableFirewall';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Privateprofile' -Name 'DefaultInboundAction';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Privateprofile' -Name 'DefaultOutboundAction';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Privateprofile' -Name 'DisableNotifications';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Privateprofile\Logging' -Name 'LogFilePath';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Privateprofile\Logging' -Name 'LogFileSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Privateprofile\Logging' -Name 'LogDroppedPackets';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Privateprofile\Logging' -Name 'LogSuccessfulConnections';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile' -Name 'EnableFirewall';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile' -Name 'DefaultInboundAction';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile' -Name 'DefaultOutboundAction';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile' -Name 'DisableNotifications';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile' -Name 'AllowLocalPolicyMerge';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile' -Name 'AllowLocalIPsecPolicyMerge';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile\Logging' -Name 'LogFilePath';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile\Logging' -Name 'LogFileSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile\Logging' -Name 'LogDroppedPackets';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Publicprofile\Logging' -Name 'LogSuccessfulConnections';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows Nt\Currentversion\Winlogon\Gpextensions\{D76B9641-3288-4F75-942D-087De603E3Ea}' -Name 'DllName';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft Services\Admpwd' -Name 'PwdExpirationProtectionEnabled';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft Services\Admpwd' -Name 'AdmPwdEnabled';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft Services\Admpwd' -Name 'PasswordComplexity';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft Services\Admpwd' -Name 'PasswordLength';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft Services\Admpwd' -Name 'PasswordAgeDays';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Netbt\Parameters' -Name 'NodeType';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows Nt\Currentversion\Winlogon' -Name 'AutoAdminLogon';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Tcpip6\Parameters' -Name 'DisableIPSourceRouting';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Tcpip\Parameters' -Name 'DisableIPSourceRouting';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Tcpip\Parameters' -Name 'EnableICMPRedirect';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Netbt\Parameters' -Name 'nonamereleaseondemand';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Session Manager' -Name 'SafeDllSearchMode';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows Nt\Currentversion\Winlogon' -Name 'ScreenSaverGracePeriod';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Eventlog\Security' -Name 'WarningLevel';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient' -Name 'DoHPolicy';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Nt\Dnsclient' -Name 'EnableMulticast';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Network Connections' -Name 'NC_AllowNetBridge_NLA';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Network Connections' -Name 'NC_StdDomainUserSetLocation';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Networkprovider\Hardenedpaths' -Name '\\*\NETLOGON';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Networkprovider\Hardenedpaths' -Name '\\*\SYSVOL';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Wcmsvc\Grouppolicy' -Name 'fMinimizeConnections';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System' -Name 'LocalAccountTokenFilterPolicy';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Lanmanworkstation' -Name 'DependOnService';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Mrxsmb10' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Services\Lanmanserver\Parameters' -Name 'SMB1';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Session Manager\Kernel' -Name 'DisableExceptionChainValidation';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers\PointAndPrint' -Name 'RestrictDriverInstallationToAdministrators';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Control\Securityproviders\Wdigest' -Name 'UseLogonCredential';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers\PointAndPrint' -Name 'NoWarningNoElevationOnInstall';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers\PointAndPrint' -Name 'UpdatePromptSettings';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System\Audit' -Name 'ProcessCreationIncludeCmdLine_Enabled';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\CredSSP\Parameters' -Name 'AllowEncryptionOracle';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Device Metadata' -Name 'PreventDeviceMetadataFromNetwork';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\Currentcontrolset\Policies\Earlylaunch' -Name 'DriverLoadPolicy';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Group Policy\{35378Eac-683F-11D2-A89A-00C04Fbbcfa2}' -Name 'NoBackgroundPolicy';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Group Policy\{35378Eac-683F-11D2-A89A-00C04Fbbcfa2}' -Name 'NoGPOListChanges';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Nt\Printers' -Name 'DisableWebPnPDownload';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Explorer' -Name 'NoWebServices';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'DontDisplayNetworkSelectionUI';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'DontEnumerateConnectedUsers';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'EnumerateLocalUsers';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'DisableLockScreenAppNotifications';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\System' -Name 'BlockDomainPicturePassword';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'AllowDomainPINLogon';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Power\Powersettings\0E796Bdb-100D-47D6-A2D5-F7D2Daa51F51' -Name 'DCSettingIndex';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Power\Powersettings\0E796Bdb-100D-47D6-A2D5-F7D2Daa51F51' -Name 'ACSettingIndex';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services' -Name 'fAllowUnsolicited';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services' -Name 'fAllowToGetHelp';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Nt\Rpc' -Name 'EnableAuthEpResolution';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Explorer' -Name 'NoAutoplayfornonVolume';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Explorer' -Name 'NoAutorun';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Explorer' -Name 'NoDriveTypeAutoRun';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Credui' -Name 'DisablePasswordReveal';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Credui' -Name 'EnumerateAdministrators';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Syssettings' -Name 'AntiDetours';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Syssettings' -Name 'BannedFunctions';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Syssettings' -Name 'DeepHooks';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Syssettings' -Name 'ExploitAction';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Internet Explorer\iexplore.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\7-Zip\7z.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\7-Zip\7zFM.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\7-Zip\7zG.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Adobe\Adobe Photoshop CS*\Photoshop.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Foxit Reader\Foxit Reader.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Google\Chrome\Application\chrome.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Google\Google Talk\googletalk.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\iTunes\iTunes.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Microsoft Lync\communicator.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\mIRC\mirc.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Mozilla Firefox\firefox.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Mozilla Firefox\plugin-container.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Mozilla Thunderbird\plugin-container.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Opera\*\opera.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Opera\opera.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Pidgin\pidgin.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\QuickTime\QuickTimePlayer.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Real\RealPlayer\realconverter.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Real\RealPlayer\realplay.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Safari\Safari.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\SkyDrive\SkyDrive.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Skype\Phone\Skype.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\VideoLAN\VLC\vlc.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Winamp\winamp.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Windows Live\Mail\wlmail.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Windows Live\Photo Gallery\WLXPhotoGallery.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Windows Live\Writer\WindowsLiveWriter.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Windows Media Player\wmplayer.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\WinRAR\rar.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\WinRAR\unrar.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\WinRAR\winrar.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\WinZip\winzip32.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\WinZip\winzip64.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Adobe\*\Reader\AcroRd32.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Adobe\Acrobat*\Acrobat\Acrobat.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Java\jre*\bin\java.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Java\jre*\bin\javaw.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Java\jre*\bin\javaws.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\OFFICE1*\EXCEL.EXE';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\OFFICE1*\INFOPATH.EXE';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\OFFICE1*\LYNC.EXE';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\OFFICE1*\MSACCESS.EXE';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\OFFICE1*\MSPUB.EXE';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\OFFICE1*\OIS.EXE';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\OFFICE1*\OUTLOOK.EXE';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\OFFICE1*\POWERPNT.EXE';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\OFFICE1*\PPTVIEW.EXE';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\OFFICE1*\VISIO.EXE';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\OFFICE1*\VPREVIEW.EXE';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\OFFICE1*\WINWORD.EXE';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Defaults' -Name '*\Windows NT\Accessories\wordpad.exe';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Syssettings' -Name 'ASLR';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Syssettings' -Name 'DEP';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Emet\Syssettings' -Name 'SEHOP';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Eventlog\Application' -Name 'Retention';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Eventlog\Application' -Name 'MaxSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Eventlog\Security' -Name 'Retention';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Eventlog\Security' -Name 'MaxSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Eventlog\Setup' -Name 'Retention';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Eventlog\Setup' -Name 'MaxSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Eventlog\System' -Name 'Retention';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Eventlog\System' -Name 'MaxSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Spynet' -Name 'LocalSettingOverrideSpynetReporting';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection' -Name 'DisableIOAVProtection';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection' -Name 'DisableRealtimeMonitoring';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection' -Name 'DisableBehaviorMonitoring';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection' -Name 'DisableScriptScanning';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Scan' -Name 'DisableRemovableDriveScanning';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Scan' -Name 'DisableEmailScanning';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender' -Name 'DisableAntiSpyware';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'EnableSmartScreen';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Explorer' -Name 'NoDataExecutionPrevention';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Explorer' -Name 'NoHeapTerminationOnCorruption';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Explorer' -Name 'PreXPSP2ShellProtocolBehavior';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Onedrive' -Name 'DisableFileSyncNGSC';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Onedrive' -Name 'DisableFileSync';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services' -Name 'DisablePasswordSaving';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services' -Name 'fDisableCdm';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services' -Name 'fPromptForPassword';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name 'fEncryptRPCTraffic';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name 'SecurityLayer';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name 'UserAuthentication';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services' -Name 'MinEncryptionLevel';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services' -Name 'DeleteTempDirsOnExit';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services' -Name 'PerSessionTempDir';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Feeds' -Name 'DisableEnclosureDownload';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Windows Search' -Name 'AllowIndexingEncryptedStoresOrItems';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Windows Error Reporting\Consent' -Name 'DefaultConsent';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Installer' -Name 'EnableUserControl';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Installer' -Name 'AlwaysInstallElevated';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Powershell\Scriptblocklogging' -Name 'EnableScriptBlockLogging';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Powershell\Transcription' -Name 'EnableTranscripting';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Client' -Name 'AllowBasic';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Client' -Name 'AllowUnencryptedTraffic';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Winrm\Client' -Name 'AllowDigest';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Winrm\Service' -Name 'AllowBasic';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Winrm\Service' -Name 'AllowUnencryptedTraffic';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Winrm\Service' -Name 'DisableRunAs';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Windowsupdate\Au' -Name 'NoAutoUpdate';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Windowsupdate\Au' -Name 'ScheduledInstallDay';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Windowsupdate\Au' -Name 'NoAutoRebootWithLoggedOnUsers';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop' -Name 'ScreenSaveActive';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop' -Name 'ScreenSaverIsSecure';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop' -Name 'ScreenSaveTimeOut';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Policies\Microsoft\Windows\Currentversion\Pushnotifications' -Name 'NoToastApplicationNotificationOnLockScreen';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Microsoft\Windows\Currentversion\Policies\Attachments' -Name 'SaveZoneInformation';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Microsoft\Windows\Currentversion\Policies\Attachments' -Name 'ScanWithAntiVirus';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Microsoft\Windows\Currentversion\Policies\Explorer' -Name 'NoInplaceSharing';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Policies\Microsoft\Windows\Installer' -Name 'AlwaysInstallElevated';Write-Output '====';
net accounts | select-string -pattern 'Lockout duration';
Write-Output '====';
net accounts | select-string -pattern 'Lockout threshold';
Write-Output '====';
net accounts | select-string -pattern 'Lockout observation window';Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeTrustedCredManAccessPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeNetworkLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeTcbPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeIncreaseQuotaPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeInteractiveLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeRemoteInteractiveLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeBackupPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeSystemTimePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeTimeZonePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeCreatePagefilePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeCreateTokenPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeCreateGlobalPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeCreatePermanentPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeCreateSymbolicLinkPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeCreateSymbolicLinkPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeDebugPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeDenyNetworkLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeDenyBatchLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeDenyServiceLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeDenyInteractiveLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeDenyRemoteInteractiveLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeEnableDelegationPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeRemoteShutdownPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeAuditPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeImpersonatePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeImpersonatePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeIncreaseBasePriorityPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeLoadDriverPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeLockMemoryPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeSecurityPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeReLabelPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeSystemEnvironmentPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeManageVolumePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeProfileSingleProcessPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeSystemProfilePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeAssignPrimaryTokenPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeRestorePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeShutdownPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeTakeOwnershipPrivilege';Write-Output '====';
net user administrator | select-string -pattern 'Account active';
Write-Output '====';
net user guest | select-string -pattern 'Account active';
Write-Output '===='
net user administrator | select-string -pattern 'User name';
Write-Output '====';
net user guest | select-string -pattern 'User name';Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System' -Name 'LegalNoticeText';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System' -Name 'LegalNoticeCaption';Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'LSAAnonymousNameLookup =';Write-Output '====';
auditpol /get /subcategory:'Credential Validation' | select-string -pattern 'Credential Validation';
Write-Output '====';
auditpol /get /subcategory:'Application Group Management' | select-string -pattern 'Application Group Management';
Write-Output '====';
auditpol /get /subcategory:'Security Group Management' | select-string -pattern 'Security Group Management';
Write-Output '====';
auditpol /get /subcategory:'User Account Management' | select-string -pattern 'User Account Management';
Write-Output '====';
auditpol /get /subcategory:'Process Creation' | select-string -pattern 'Process Creation';
Write-Output '====';
auditpol /get /subcategory:'Account Lockout' | select-string -pattern 'Account Lockout';
Write-Output '====';
auditpol /get /subcategory:'Logoff' | select-string -pattern 'Logoff';
Write-Output '====';
auditpol /get /subcategory:'Logon' | select-string -pattern 'Logon';
Write-Output '====';
auditpol /get /subcategory:'Other Logon/Logoff Events' | select-string -pattern 'Other Logon/Logoff Events';
Write-Output '====';
auditpol /get /subcategory:'Special Logon' | select-string -pattern 'Special Logon';
Write-Output '====';
auditpol /get /subcategory:'Detailed File Share' | select-string -pattern 'Detailed File Share';
Write-Output '====';
auditpol /get /subcategory:'File Share' | select-string -pattern 'File Share';
Write-Output '====';
auditpol /get /subcategory:'Other Object Access Events' | select-string -pattern 'Other Object Access Events';
Write-Output '====';
auditpol /get /subcategory:'Removable Storage' | select-string -pattern 'Removable Storage';
Write-Output '====';
auditpol /get /subcategory:'Audit Policy Change' | select-string -pattern 'Audit Policy Change';
Write-Output '====';
auditpol /get /subcategory:'Authentication Policy Change' | select-string -pattern 'Authentication Policy Change';
Write-Output '====';
auditpol /get /subcategory:'Authorization Policy Change' | select-string -pattern 'Authorization Policy Change';
Write-Output '====';
auditpol /get /subcategory:'MPSSVC Rule-Level Policy Change' | select-string -pattern 'MPSSVC Rule-Level Policy Change';
Write-Output '====';
auditpol /get /subcategory:'Other Policy Change Events' | select-string -pattern 'Other Policy Change Events';
Write-Output '====';
auditpol /get /subcategory:'Sensitive Privilege Use' | select-string -pattern 'Sensitive Privilege Use';
Write-Output '====';
auditpol /get /subcategory:'IPsec Driver' | select-string -pattern 'IPsec Driver';
Write-Output '====';
auditpol /get /subcategory:'Other System Events' | select-string -pattern 'Other System Events';
Write-Output '====';
auditpol /get /subcategory:'Security State Change' | select-string -pattern 'Security State Change';
Write-Output '====';
auditpol /get /subcategory:'Security System Extension' | select-string -pattern 'Security System Extension';
Write-Output '====';
auditpol /get /subcategory:'System Integrity' | select-string -pattern 'System Integrity';Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System' -Name 'DisableBkGndGroupPolicy';Write-Output '====';
(Get-WmiObject -Class Win32_ComputerSystem).DomainRole;